version: '3.8'

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: ${HOSTNAME}_cadvisor
    ports:
      - '8080:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    environment:
      - HOSTNAME=${HOSTNAME}
    entrypoint: ["/entrypoint.sh"]
    restart: unless-stopped

volumes:
  cadvisor_data: