version: '3.7'

services:
  cadvisor:
    build: .
    container_name: ${HOSTNAME}_cadvisor
    ports:
      - '8080:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    environment:
      - HOSTNAME=${HOSTNAME}
    restart: unless-stopped